export const RESPONSE_CODES = {
    success: [200],
    failure: [400, 401, 404, 500],
    custom: [409],
};

export const IncomeTypes = {
    SALARIED: 1,
    SELF_EMPLOYED: 2,
};

export const ERROR_MESSAGES = {
    multipleOf100: 'Amount should be multiple of 100',
    timeout: 'Facing issues in connection. Try again later!',
    email_verified:
        'Email verification pending: Check your inbox or navigate to Profile> View Details > Personal to generate a new link.',
    bank_account: 'Bank Account Not Present',
    terms: 'Agree to Terms',
    network: 'Network Error!',
    token: 'Session Expired, Please Relogin!',
    login: 'Please login!',
    default: 'Something Went Wrong!',
    reportDate: 'From Date cannot be greater Than To Date',
    INSUFFICIENT_FUND: 'Insufficient Funds',
};

export const INDIAN_STATES = [
    {
        value: 'Andaman and Nicobar Islands',
        label: 'Andaman and Nicobar Islands',
    },
    { value: 'Andhra Pradesh', label: 'Andhra Pradesh' },
    { value: 'Arunachal Pradesh', label: 'Arunachal Pradesh' },
    { value: 'Assam', label: 'Assam' },
    { value: 'Bihar', label: 'Bihar' },
    { value: 'Chandigarh', label: 'Chandigarh' },
    { value: 'Chhattisgarh', label: 'Chhattisgarh' },
    {
        value: 'Dadra and Nagar Haveli and Daman and Diu',
        label: 'Dadra and Nagar Haveli and Daman and Diu',
    },
    { value: 'Delhi', label: 'Delhi' },
    { value: 'Goa', label: 'Goa' },
    { value: 'Gujarat', label: 'Gujarat' },
    { value: 'Haryana', label: 'Haryana' },
    { value: 'Himachal Pradesh', label: 'Himachal Pradesh' },
    { value: 'Jammu and Kashmir', label: 'Jammu and Kashmir' },
    { value: ' Jharkhand', label: 'Jharkhand' },
    { value: 'Karnataka', label: 'Karnataka' },
    { value: 'Kerala', label: 'Kerala' },
    { value: 'Ladakh', label: 'Ladakh' },
    { value: 'Lakshadweep', label: 'Lakshadweep' },
    { value: 'Madhya Pradesh', label: 'Madhya Pradesh' },
    { value: 'Maharashtra', label: 'Maharashtra' },
    { value: 'Manipur', label: 'Manipur' },
    { value: 'Meghalaya', label: 'Meghalaya' },
    { value: 'Mizoram', label: 'Mizoram' },
    { value: 'Nagaland', label: 'Nagaland' },
    { value: 'Odisha', label: 'Odisha' },
    { value: 'Puducherry', label: 'Puducherry' },
    { value: 'Punjab', label: 'Punjab' },
    { value: 'Rajasthan', label: 'Rajasthan' },
    { value: 'Sikkim', label: 'Sikkim' },
    { value: 'Tamil Nadu', label: 'Tamil Nadu' },
    { value: 'Telangana', label: 'Telangana' },
    { value: 'Tripura', label: 'Tripura' },
    { value: 'Uttar Pradesh', label: 'Uttar Pradesh' },
    { value: 'Uttarakhand', label: 'Uttarakhand' },
    { value: 'West Bengal', label: 'West Bengal' },
];

export const DESIGNATION_OPTIONS = [
    'Software Engineer',
    'Data Scientist',
    'Product Manager',
    'Marketing Manager',
    'Human Resources Manager',
    'Financial Analyst',
    'Business Development Manager',
    'Project Manager',
    'Quality Assurance Engineer',
    'User Experience Designer',
    'Graphic Designer',
    'Content Writer',
    'Sales Representative',
    'Customer Success Manager',
    'Account Manager',
    'Operations Manager',
    'Supply Chain Manager',
    'Logistics Manager',
    'Network Administrator',
    'Security Analyst',
    'Database Administrator',
    'Systems Engineer',
    'Help Desk Analyst',
    'Technical Support Specialist',
    'Marketing Analyst',
    'Social Media Manager',
    'Search Engine Optimization Specialist',
    'Content Marketing Specialist',
    'Public Relations Specialist',
    'Web Developer',
    'Mobile Developer',
    'Full Stack Developer',
    'Back-End Developer',
    'Front-End Developer',
    'DevOps Engineer',
    'Data Engineer',
    'Machine Learning Engineer',
    'Artificial Intelligence Engineer',
    'Business Analyst',
    'Management Consultant',
    'Human Resources Consultant',
    'Financial Consultant',
    'Lawyer',
    'Doctor',
    'Nurse',
    'Teacher',
    'Accountant',
    'Architect',
    'Engineer',
    'Marketing Specialist',
    'Sales Associate',
    'Customer Service Representative',
    'Executive Assistant',
    'Human Resources Assistant',
];

export const LOAN_REFERENCE_PERSONAL_TYPES = [
    'FATHER',
    'MOTHER',
    'SPOUSE',
    'BROTHER',
    'SISTER',
    'SON',
    'DAUGHTER',
    'FRIEND',
];

export const LOAN_REFERENCE_PROFESSIONAL_TYPES = [
    'REPORTING MANAGER',
    'TEAM MEMBER',
    'HR',
    'EX COLLEGUE',
];

export const DOCUMENT_LIST = [
    'PAN',
    'AADHAAR_FRONT',
    'AADHAAR_BACK',
    'PASSPORT_FRONT',
    'PASSPORT_BACK',
    'DRIVING_LICENSE',
    'CHEQUE',
    'RENT_AGREEMENT',
    'PROPERTY_AGREEMENT',
    'WET_SIGNATURE',
    'BANK_PASSBOOK',
    'BANK_STATEMENT',
    'VOTER_ID',
    'SALARY_SLIP',
    'ELECTRICITY_BILL',
    'GAS_BILL',
    'FORM_16',
    'ITR',
];

export const DOCUMENT_PURPOSE = [
    'IDENTITY',
    'ADDRESS',
    'BANK VERIFICATION',
    'ON BOARDING',
    'INCOME',
    'PROPERTY',
    'BANK MANDATE',
];
